definitions:
  dto.CreateLoginAccessToken:
    properties:
      token:
        type: string
    type: object
  dto.LoginParam:
    properties:
      password:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 로그인
      parameters:
      - description: login param
        in: body
        name: Auth
        required: true
        schema:
          $ref: '#/definitions/dto.LoginParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateLoginAccessToken'
        "404":
          description: Not Found
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Login
      tags:
      - Authentication
  /logout:
    post:
      consumes:
      - application/json
      description: 로그아웃
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Logout
      tags:
      - Authentication
  /reissuance:
    post:
      consumes:
      - application/json
      description: Login Access Token 재발급
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateLoginAccessToken'
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Ressuance Login Access Token
      tags:
      - Authentication
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
