FROM golang:alpine AS stage
WORKDIR /src/streaming
COPY . .

RUN apk update && \
  apk upgrade && \
  apk add --update-cache tzdata

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-s' -o main main.go

FROM scratch

WORKDIR /src/streaming

COPY --from=stage /src/streaming/adapter/view /src/streaming/adapter/view
COPY --from=stage /src/streaming/static /src/streaming/static
COPY --from=stage /src/streaming/main /src/streaming/main
COPY --from=stage /usr/local/go/lib/time/zoneinfo.zip /usr/local/go/lib/time/zoneinfo.zip
ENV TZ=Asia/Seoul ZONEINFO=/zoneinfo.zip

CMD [ "/src/streaming/main" ]
